### ISSUE TITLE
Getting Error on Example Build

### ISSUE THREAD

**Issue by canewsin** [cloudpeers/ffi-gen#54]
Log: 
```
error: failed to run custom build command for `api v0.1.0 (C:\Users\PramUkesh\Documents\SkyNet Project\ffi-gen\example)`

Caused by:
  process didn't exit successfully: `C:\Users\PramUkesh\Documents\SkyNet Project\ffi-gen\target\debug\build\api-27b545f289e6be4d\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=C:\Users\PramUkesh\Documents\SkyNet Project\ffi-gen\example\api.rsh

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:  --> 2:18
    |
  2 | fn hello_world();␍␊
    |                  ^---
    |
    = expected EOI, item_docs, or function

  Stack backtrace:
     0: std::backtrace_rs::backtrace::dbghelp::trace
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98    
     1: std::backtrace_rs::backtrace::trace_unsynchronized
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66        
     2: std::backtrace::Backtrace::create
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\/library\std\src\backtrace.rs:328
     3: std::backtrace::Backtrace::capture
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\/library\std\src\backtrace.rs:296
     4: anyhow::error::impl$1::from<pest::error::Error<enum$<ffi_gen::parser::Rule> > >
               at C:\Users\PramUkesh\.cargo\registry\src\github.com-1ecc6299db9ec823\anyhow-1.0.51\src\error.rs:530
     5: core::result::impl$37::from_residual<ffi_gen::parser::Interface,pest::error::Error<enum$<ffi_gen::parser::Rule> >,anyhow::Error>
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\library\core\src\result.rs:1976
     6: ffi_gen::parser::Interface::parse
               at C:\Users\PramUkesh\Documents\SkyNet Project\ffi-gen\src\parser.rs:21
     7: ffi_gen::FfiGen::new<ref$<std::path::PathBuf> >
               at C:\Users\PramUkesh\Documents\SkyNet Project\ffi-gen\src\lib.rs:28
     8: build_script_build::main
               at .\build.rs:11
     9: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\library\core\src\ops\function.rs:227
    10: std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\library\std\src\sys_common\backtrace.rs:123
    11: std::rt::lang_start::closure$0<tuple$<> >
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\library\std\src\rt.rs:145
    12: core::ops::function::impls::impl$2::call_once
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\library\core\src\ops\function.rs:259
    13: std::panicking::try::do_call
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\/library\std\src\panicking.rs:406
    14: std::panicking::try
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\/library\std\src\panicking.rs:370
    15: std::panic::catch_unwind
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\/library\std\src\panic.rs:133
    16: std::rt::lang_start_internal::closure$2
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\/library\std\src\rt.rs:128
    17: std::panicking::try::do_call
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\/library\std\src\panicking.rs:406
    18: std::panicking::try
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\/library\std\src\panicking.rs:370
    19: std::panic::catch_unwind
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\/library\std\src\panic.rs:133
    20: std::rt::lang_start_internal
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\/library\std\src\rt.rs:128
    21: std::rt::lang_start<tuple$<> >
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\library\std\src\rt.rs:144
    22: main
    23: invoke_main
               at d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    24: __scrt_common_main_seh
               at d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    25: BaseThreadInitThunk
    26: RtlUserThreadStart', example\build.rs:11:37
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\/library\std\src\panicking.rs:498
     1: core::panicking::panic_fmt
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\/library\core\src\panicking.rs:107
     2: core::result::unwrap_failed
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\/library\core\src\result.rs:1661
     3: enum$<core::result::Result<ffi_gen::FfiGen,anyhow::Error> >::unwrap<ffi_gen::FfiGen,anyhow::Error>
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\library\core\src\result.rs:1342
     4: build_script_build::main
               at .\build.rs:11
     5: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
               at /rustc/c5ecc157043ba413568b09292001a4a74b541a4e\library\core\src\ops\function.rs:227
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by dvc94ch** [comment]
are you on windows? saw this error when trying to build it on windows in ci, unfortunately I don't have a windows machine to test it.

- [0] https://github.com/cloudpeers/tlfs/issues/108

**Comment by canewsin** [comment]
This works


/// Prints a friendly greeting to stdout.
fn hello_world();///
/// Returns a future that prints a friendly
/// greeting to stdout.
fn async_hello_world() -> Future<Result<u8>>;

**Comment by dvc94ch** [comment]
Can you test changing the example to dos style new lines \r\n?

**Comment by canewsin** [comment]
There is problem while parsing ␍␊ characters, tries above suggestion
got
```
fn hello_world();\r\n␍␊
    |                  ^---
    |
    = expected EOI, item_docs, or function
```

**Comment by canewsin** [comment]
grammer.pest need modification ?

**Comment by dvc94ch** [comment]
do you have the unix2dos command on windows? was suggesting running that on the example

**Comment by canewsin** [comment]
will try it

**Comment by dvc94ch** [comment]
or alternatively maybe this works?

change `WHITESPACE = _{ " " | "\t" | "\n" }` to `WHITESPACE = _{ " " | "\t" | "\n" | "\r" }` in grammar.pest

**Comment by canewsin** [comment]
Works

**Comment by canewsin** [comment]
Also Example has hello_world, but bindings as now as per dart naming lints helloWorld()

**Comment by dvc94ch** [comment]
that's expected. the rsh file contains the names in "rust style". the dart and js backends convert it to their respective language styles and sanitizing identifiers that match keywords.

**Comment by canewsin** [comment]
Any thanks for work who ever made it, took week for automation of rust to dart, still has some work, seen your flutter comment on libp2p, found this.

**Comment by canewsin** [comment]
> that's expected. the rsh file contains the names in "rust style". the dart and js backends convert it to their respective language styles and sanitizing identifiers that match keywords.

expected that, suggesting to update example

**Comment by dvc94ch** [comment]
ah I remember you now. you were the guy doing advertising for zeronet in the ipfs-embed riot channel. zeronet uses libp2p now?

**Comment by canewsin** [comment]
Yeah that's me, planned to upgrade, currently working on DecentNet Project. similar to ZeroNet Protocol but its next gen to it and portable.

**Comment by dvc94ch** [comment]
have you seen https://github.com/cloudpeers/tlfs? It's a rust framework for building local first applications with support for flutter and react

**Comment by canewsin** [comment]
Just seen but didn't understood what's it for.

**Comment by canewsin** [comment]
If i remember correctly, i saw this type of idea some where, like data caching.

**Comment by dvc94ch** [comment]
docs and examples are still pretty poor, will start working on a website and impoved examples tutorials soon. it's basically a p2p document database (kind of like mongodb) with support for automatic schema migration and fine grained access control. We've just been working on it for a couple of months now so the simple flutter demo is probably the best place to look to understand what it does: https://github.com/cloudpeers/flutter-todoapp/tree/master/lib

**Comment by dvc94ch** [comment]
no data caching. it's based on delta crdts

**Comment by canewsin** [comment]
I do work with flutter and rust, you reduced the pain of porting(7 days still wip for my work), will try to contribute to ffigen if possible.

**Comment by canewsin** [comment]
Yes, now i remember you, I saw on rkyv conversation, you tried any port for rkyv for dart
> - assets/todoapp.tlfs.rkyv

**Comment by canewsin** [comment]
Currently using prost for communication for ffi layer due to rust only nature for rkyv

**Comment by dvc94ch** [comment]
don't thinks so. we use rkyv but didn't port it to dart no. maybe you remember me as the main author of ipfs-embed/rust-ipfs where you pitched zeronet :)

**Comment by canewsin** [comment]
.rkyv is this an extension ?

**Comment by dvc94ch** [comment]
we use it for compiled schemas, but it's not an official extension. reading it with anything other than tlfs won't work

**Comment by canewsin** [comment]
Nice to see the similar idea we both have, just seen the discussions on riot, also similar timeline, building for private sponsor currently as of now. Will Open Source the work in future.
