### ISSUE TITLE
Errors with 32bit target

### ISSUE THREAD

**Issue by gnunicorn** [cloudpeers/ffi-gen#69]
Running with an x86 32bit emulator I couldn't get this to work. even something as simple as echoing the same string back, like below, failed.
```// api.rsh
fn echo(inp: string) -> Result<string>;
```
```# api.rs
pub fn echo(inp: String) -> Result<String> {
    Ok(String::from(inp))
}
```

It fails when trying to read back the result string:
```
E/flutter ( 4879): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): length must be in the range [0, 1073741823].
E/flutter ( 4879): #0      _checkExternalTypedDataLength (dart:ffi-patch/ffi_patch.dart:58:5)
E/flutter ( 4879): #1      Uint8Pointer.asTypedList (dart:ffi-patch/ffi_patch.dart:624:5)
E/flutter ( 4879): #2      Api.echo
package:effektio_flutter_sdk/effektio_flutter_sdk.dart:393
E/flutter ( 4879): #3      main
package:effektio/main.dart:9
```

And putting a `print("${tmp10};${tmp11};${tmp12}");` into the generated dart-code also shows why: `I/flutter ( 4879):-5868786620503136931;-5095886506439946255;-2008385391117589139` are really not valid pointer and size values. I think there's some type-mixup happening as the dart-code is looking at it with a 64bit data-lense while the code that is generated for 32bit rust uses i32 and u32 ...

**Comment by dvc94ch** [comment]
dart doesn't support cross compiling afaik, can you elaborate on how you built it? seems like you have 64bit dart code loading a 32bit library? note that you'll have to regenerate the bindings for a 32bit library.

**Comment by dvc94ch** [comment]
[here](https://github.com/cloudpeers/ffi-gen/blob/master/src/abi.rs#L218) we select the type based on the target_pointer_width which is detected in the macro and it works with wasm32, so not sure what the issue might be.

**Comment by dvc94ch** [comment]
saddly our infrastructure is quite complicated and not trivial to get it to work. if you're trying to evaluate the tlfs platform, I'd suggest sticking to supported targets and build configurations. if you want to use ffi-gen in your own project, a small test case would help. if you have some other needs consulting is available.

**Comment by gnunicorn** [comment]
No worries, 64bit it is for not (I am not sure I'll need the 32bit architecture yet). If I do come across the issue again, I'll raise more info and/or a PR about it. Just wanted to have this already noted for reference.
